<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT3yisrp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT3yisrp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT3yisrp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT3yisrp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT3yisrp\appProdProjectContainer([
    'container.build_hash' => 'T3yisrp',
    'container.build_id' => '1eab1348',
    'container.build_time' => 1638015673,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT3yisrp');
