<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLihqtqp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLihqtqp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLihqtqp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLihqtqp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLihqtqp\appDevDebugProjectContainer([
    'container.build_hash' => 'Lihqtqp',
    'container.build_id' => 'b4a75c2c',
    'container.build_time' => 1637831013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLihqtqp');
